name: ${project.name}
version: ${project.version}
website: ${project.url}
author: ${author}

main: ${project.groupId}.${project.artifactId}.${project.name}
depend: [NiftyLibrary]

commands:
  servers:
    description: Opens a chest and/or lists servers to connect to
    usage: /<command> [server|chest|list]
    aliases: [nservers, nserver, server, serv, serv, ns]

permissions:
  niftyservers.*:
    description: Gives access to all plugin features and commands
    children:
      niftyservers.chest:
        description: Allows you to view the server selection screen
        default: true
      niftyservers.server.*:
        description: Gives you access to all servers
        default: true
        children:
          niftyservers.server:
            description: Allows you to run the server command
      niftyservers.restricted.server.*:
        description: Allows you to list and access all restricted servers