name: NiftyServers
version: 2.0
website: http://netcoding.net/
author: Brian Graham

main: net.netcoding.niftyservers.NiftyServers
depend: [NiftyBukkit]

commands:
  sreload:
    description: Reloads the config
    usage: /<command>
    permission: niftyservers.reload
  server:
    description: Opens a chest and/or lists servers to connect to
    usage: /<command> [server|list]
    aliases: [serv, ns, s]

permissions:
  niftyservers.*:
    description: Gives access to all plugin features and commands
    children:
      niftyservers.chest:
        description: Allows you to place and use blacklisted items
        default: true
      niftyservers.list:
        description: Allows you to spawn or pull items from the creative inventory, without lore
        default: true
      niftyservers.restricted.*:
        description: Allows you to access all restricted servers
      niftyservers.reload:
        description: Allows you to reload the plugin config
      niftyservers.server:
        description: Allows you to run the server command
        default: true
      niftyservers.server.*:
        description: Gives you access to all servers
        default: true
        children:
          niftyservers.server: true